import { AVAILABLE_FONTS } from './font-definitions';

export interface GenerateOptions {
  includeHeader?: boolean;
  shadowComponents?: string[];
}

const HEADER = `/**
 * Kigumi Studio Theme
 * Generated by Kigumi Studio - https://kigumi.style/kigumi-studio
 * Compatible with: kigumi CLI theme.css
 */`;

function formatBlock(
  selector: string,
  properties: Record<string, string>
): string {
  const entries = Object.entries(properties);
  if (entries.length === 0) return '';

  const lines = entries.map(([key, value]) => `  ${key}: ${value};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

/**
 * Generate CSS rules for components that should receive box-shadow.
 */
function formatShadowRules(classNames: string[]): string {
  if (classNames.length === 0) return '';

  const rules = classNames
    .map((className) => `.${className} {\n  box-shadow: var(--wa-shadow-m);\n}`)
    .join('\n\n');

  return `/* Component Shadows */\n${rules}`;
}

/**
 * Convert hex color to rgb() format with opacity.
 */
function hexToRgb(hex: string, opacity: number): string {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return `rgb(0 0 0 / ${opacity})`;

  const r = parseInt(result[1], 16);
  const g = parseInt(result[2], 16);
  const b = parseInt(result[3], 16);

  return `rgb(${r} ${g} ${b} / ${opacity})`;
}

/**
 * Extract Bunny Fonts import URLs from font family values.
 * Looks at --wa-font-family-* properties and finds matching Bunny URLs.
 */
function extractFontImports(
  lightProperties: Record<string, string>,
  darkProperties: Record<string, string>
): string[] {
  const imports = new Set<string>();

  // Font family CSS variables to check
  const fontVars = [
    '--wa-font-family-body',
    '--wa-font-family-heading',
    '--wa-font-family-code',
    '--wa-font-family-longform',
  ];

  fontVars.forEach((cssVar) => {
    const lightValue = lightProperties[cssVar];
    const darkValue = darkProperties[cssVar];

    // Check both light and dark mode values
    [lightValue, darkValue].forEach((value) => {
      if (!value) return;

      // Find matching font in AVAILABLE_FONTS
      const font = AVAILABLE_FONTS.find((f) => f.value === value);
      if (font?.bunnyUrl) {
        imports.add(font.bunnyUrl);
      }
    });
  });

  return Array.from(imports);
}

/**
 * Process properties to combine shadow color + opacity.
 * Web Awesome expects --wa-color-shadow as rgb(r g b / opacity).
 */
function processShadowProperties(
  properties: Record<string, string>
): Record<string, string> {
  const processed = { ...properties };

  // If both shadow color and opacity exist, combine them
  if (processed['--wa-color-shadow'] && processed['--wa-shadow-opacity']) {
    const colorHex = processed['--wa-color-shadow'];
    const opacity = parseFloat(processed['--wa-shadow-opacity']);

    // Combine into Web Awesome format: rgb(r g b / opacity)
    processed['--wa-color-shadow'] = hexToRgb(colorHex, opacity);

    // Remove separate opacity property (it's now embedded in color)
    delete processed['--wa-shadow-opacity'];
  }

  return processed;
}

/**
 * Generate a CSS theme string from modified light and dark properties.
 * Only includes properties that differ from defaults.
 */
export function generateThemeCSS(
  light: Record<string, string>,
  dark: Record<string, string>,
  options: GenerateOptions = {}
): string {
  const { includeHeader = true, shadowComponents = [] } = options;

  // Extract font imports automatically
  const fontImports = extractFontImports(light, dark);

  // Process shadow properties to combine color + opacity
  const processedLight = processShadowProperties(light);
  const processedDark = processShadowProperties(dark);

  const rootBlock = formatBlock(':root', processedLight);
  const darkBlock = formatBlock('.wa-dark', processedDark);
  const shadowBlock = formatShadowRules(shadowComponents);

  // Early exit if no content
  if (!rootBlock && !darkBlock && !shadowBlock && fontImports.length === 0) {
    return '';
  }

  const parts: string[] = [];

  // 1. Font Imports (FIRST - must be at top of CSS)
  if (fontImports.length > 0) {
    const importStatements = fontImports
      .map((url) => `@import url('${url}');`)
      .join('\n');
    parts.push(importStatements);
  }

  // 2. Header Comment
  if (includeHeader) {
    parts.push(HEADER);
  }

  // 3. :root Block
  if (rootBlock) {
    parts.push(rootBlock);
  }

  // 4. .wa-dark Block
  if (darkBlock) {
    parts.push(darkBlock);
  }

  // 5. Component Shadow Rules
  if (shadowBlock) {
    parts.push(shadowBlock);
  }

  return parts.join('\n\n') + '\n';
}
