/**
 * Web Awesome Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports the selected theme and applies theme classes to the <html> element.
 *
 * Current theme: awesome
 * Current palette: default
 * Current brand: purple
 *
 * To change themes, use: kigumi theme set <name>
 * To change brand color, use: kigumi brand set <color>
 */

import '@awesome.me/webawesome/dist/styles/themes/awesome.css';

import '@/styles/theme.css';

// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\bwa-theme-\S+/g, '')
    .replace(/\bwa-palette-\S+/g, '')
    .replace(/\bwa-brand-\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-awesome');
  html.classList.add('wa-palette-default');
  html.classList.add('wa-brand-purple');
}

export {};
