/**
 * Web Awesome Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports Web Awesome styles and applies theme classes to the <html> element.
 *
 * Current theme: awesome
 * Current palette: elegant
 * Current brand: orange
 *
 * To change themes, use: kigumi theme set <name>
 * To change brand color, use: kigumi brand set <color>
 */

// Note: setBasePath is not needed for Vite projects as assets are bundled correctly

// Import base Web Awesome CSS (includes all CSS variables and component styles)
import '@awesome.me/webawesome/dist/styles/webawesome.css';

// Import selected theme CSS
import '@awesome.me/webawesome/dist/styles/themes/awesome.css';

// Import Web Awesome components (registers web components)
import '@awesome.me/webawesome/dist/components/button/button.js';
import '@awesome.me/webawesome/dist/components/input/input.js';
import '@awesome.me/webawesome/dist/components/card/card.js';
import '@awesome.me/webawesome/dist/components/dialog/dialog.js';

// Import your custom theme overrides
import '@/styles/theme.css';

// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\bwa-theme-\S+/g, '')
    .replace(/\bwa-palette-\S+/g, '')
    .replace(/\bwa-brand-\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-awesome');
  html.classList.add('wa-palette-elegant');
  html.classList.add('wa-brand-orange');
}

export {};
