/**
 * GENERATED by scripts/sync-wa-pro-shim.ts. Do not edit by hand.
 *
 * Ambient module declarations for Pro-only Web Awesome import paths.
 * Templates import from the Free path (`@awesome.me/webawesome/dist/...`);
 * at materialize time the path is rewritten to `webawesome-pro/...`.
 *
 * MUST be a SCRIPT file (no top-level import/export). In a module file,
 * `declare module 'X' { ... }` becomes a module *augmentation* that
 * requires 'X' to already be known — defeating the purpose for unknown
 * Pro paths.
 */

declare module '@awesome.me/webawesome/dist/components/bar-chart/bar-chart.js' {
  export default class WaBarChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/bubble-chart/bubble-chart.js' {
  export default class WaBubbleChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/chart/chart.js' {
  export default class WaChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/combobox/combobox.js' {
  export default class WaCombobox extends HTMLElement {
    show?(): void;
    hide?(): void;
    focus?(options: FocusOptions): void;
    blur?(): void;
    setCustomValidity?(message: string): void;
    formStateRestoreCallback?(state: string | File | FormData | null, reason: 'autocomplete' | 'restore'): void;
    resetValidity?(): void;
  }
}

declare module '@awesome.me/webawesome/dist/components/doughnut-chart/doughnut-chart.js' {
  export default class WaDoughnutChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/file-input/file-input.js' {
  export default class WaFileInput extends HTMLElement {
    focus?(options: FocusOptions): void;
    blur?(): void;
    setCustomValidity?(message: string): void;
    formStateRestoreCallback?(state: string | File | FormData | null, reason: 'autocomplete' | 'restore'): void;
    resetValidity?(): void;
  }
}

declare module '@awesome.me/webawesome/dist/components/line-chart/line-chart.js' {
  export default class WaLineChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/number-input/number-input.js' {
  export default class WaNumberInput extends HTMLElement {
    focus?(options: FocusOptions): void;
    blur?(): void;
    select?(): void;
    stepUp?(): void;
    stepDown?(): void;
    setCustomValidity?(message: string): void;
    formStateRestoreCallback?(state: string | File | FormData | null, reason: 'autocomplete' | 'restore'): void;
    resetValidity?(): void;
  }
}

declare module '@awesome.me/webawesome/dist/components/pie-chart/pie-chart.js' {
  export default class WaPieChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/polar-area-chart/polar-area-chart.js' {
  export default class WaPolarAreaChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/radar-chart/radar-chart.js' {
  export default class WaRadarChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/scatter-chart/scatter-chart.js' {
  export default class WaScatterChart extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/sparkline/sparkline.js' {
  export default class WaSparkline extends HTMLElement {}
}

declare module '@awesome.me/webawesome/dist/components/toast/toast.js' {
  export type ToastCreateOptions = unknown;
  export default class WaToast extends HTMLElement {
    create?(message: string, options: ToastCreateOptions): void;
  }
}

declare module '@awesome.me/webawesome/dist/components/toast-item/toast-item.js' {
  export default class WaToastItem extends HTMLElement {
    hide?(): void;
  }
}
