/**
 * GENERATED by scripts/sync-wa-pro-shim.ts. Do not edit by hand.
 *
 * JSX intrinsic-element declarations for Pro-only Web Awesome components.
 * Mirrors Free's CustomElements shape so React 19 (`React.JSX`),
 * Vue, and global JSX fallbacks all see Pro tags with accurate ref types.
 *
 * NOTE: Both `declare module 'react'` and `declare global` augmentations
 * are intentional and additive. Critical Rule #3 in CLAUDE.md ("declare
 * global not declare module 'react'") guards against overwriting React's
 * exports, but namespace-only augmentation of JSX.IntrinsicElements is
 * the standard idiom and what WA's own custom-elements-jsx.d.ts uses.
 */

import type WaBarChart from '@awesome.me/webawesome/dist/components/bar-chart/bar-chart.js';
import type WaBubbleChart from '@awesome.me/webawesome/dist/components/bubble-chart/bubble-chart.js';
import type WaChart from '@awesome.me/webawesome/dist/components/chart/chart.js';
import type WaCombobox from '@awesome.me/webawesome/dist/components/combobox/combobox.js';
import type WaDateInput from '@awesome.me/webawesome/dist/components/date-input/date-input.js';
import type WaDatePicker from '@awesome.me/webawesome/dist/components/date-picker/date-picker.js';
import type WaDoughnutChart from '@awesome.me/webawesome/dist/components/doughnut-chart/doughnut-chart.js';
import type WaFileInput from '@awesome.me/webawesome/dist/components/file-input/file-input.js';
import type WaLineChart from '@awesome.me/webawesome/dist/components/line-chart/line-chart.js';
import type WaNumberInput from '@awesome.me/webawesome/dist/components/number-input/number-input.js';
import type WaPieChart from '@awesome.me/webawesome/dist/components/pie-chart/pie-chart.js';
import type WaPolarAreaChart from '@awesome.me/webawesome/dist/components/polar-area-chart/polar-area-chart.js';
import type WaRadarChart from '@awesome.me/webawesome/dist/components/radar-chart/radar-chart.js';
import type WaScatterChart from '@awesome.me/webawesome/dist/components/scatter-chart/scatter-chart.js';
import type WaSparkline from '@awesome.me/webawesome/dist/components/sparkline/sparkline.js';
import type WaToast from '@awesome.me/webawesome/dist/components/toast/toast.js';
import type WaToastItem from '@awesome.me/webawesome/dist/components/toast-item/toast-item.js';
import type WaVideo from '@awesome.me/webawesome/dist/components/video/video.js';
import type WaVideoPlaylist from '@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js';

export type WaBarChartProps = {
  "type"?: WaBarChart['type'];
  
  "orientation"?: WaBarChart['orientation'];
  
  "label"?: WaBarChart['label'];
  
  "description"?: WaBarChart['description'];
  
  "xLabel"?: WaBarChart['xLabel'];
  
  "yLabel"?: WaBarChart['yLabel'];
  
  "legend-position"?: WaBarChart['legendPosition'];
  
  "legendPosition"?: WaBarChart['legendPosition'];
  
  "stacked"?: WaBarChart['stacked'];
  
  "index-axis"?: WaBarChart['indexAxis'];
  
  "indexAxis"?: WaBarChart['indexAxis'];
  
  "grid"?: WaBarChart['grid'];
  
  "min"?: WaBarChart['min'];
  
  "max"?: WaBarChart['max'];
  
  "without-animation"?: WaBarChart['withoutAnimation'];
  
  "withoutAnimation"?: WaBarChart['withoutAnimation'];
  
  "without-legend"?: WaBarChart['withoutLegend'];
  
  "withoutLegend"?: WaBarChart['withoutLegend'];
  
  "without-tooltip"?: WaBarChart['withoutTooltip'];
  
  "withoutTooltip"?: WaBarChart['withoutTooltip'];
  
  "plugins"?: WaBarChart['plugins'];
  
  "dir"?: WaBarChart['dir'];
  
  "lang"?: WaBarChart['lang'];
  
  "did-ssr"?: WaBarChart['didSSR'];
  
  "didSSR"?: WaBarChart['didSSR'];
  
  "config"?: WaBarChart['config'];
  
  "chart"?: WaBarChart['chart'];
  
  "initialReflectedProperties"?: WaBarChart['initialReflectedProperties'];
  
  "internals"?: WaBarChart['internals'];

}

export type WaBubbleChartProps = {
  "type"?: WaBubbleChart['type'];
  
  "label"?: WaBubbleChart['label'];
  
  "description"?: WaBubbleChart['description'];
  
  "xLabel"?: WaBubbleChart['xLabel'];
  
  "yLabel"?: WaBubbleChart['yLabel'];
  
  "legend-position"?: WaBubbleChart['legendPosition'];
  
  "legendPosition"?: WaBubbleChart['legendPosition'];
  
  "stacked"?: WaBubbleChart['stacked'];
  
  "index-axis"?: WaBubbleChart['indexAxis'];
  
  "indexAxis"?: WaBubbleChart['indexAxis'];
  
  "grid"?: WaBubbleChart['grid'];
  
  "min"?: WaBubbleChart['min'];
  
  "max"?: WaBubbleChart['max'];
  
  "without-animation"?: WaBubbleChart['withoutAnimation'];
  
  "withoutAnimation"?: WaBubbleChart['withoutAnimation'];
  
  "without-legend"?: WaBubbleChart['withoutLegend'];
  
  "withoutLegend"?: WaBubbleChart['withoutLegend'];
  
  "without-tooltip"?: WaBubbleChart['withoutTooltip'];
  
  "withoutTooltip"?: WaBubbleChart['withoutTooltip'];
  
  "plugins"?: WaBubbleChart['plugins'];
  
  "dir"?: WaBubbleChart['dir'];
  
  "lang"?: WaBubbleChart['lang'];
  
  "did-ssr"?: WaBubbleChart['didSSR'];
  
  "didSSR"?: WaBubbleChart['didSSR'];
  
  "config"?: WaBubbleChart['config'];
  
  "chart"?: WaBubbleChart['chart'];
  
  "initialReflectedProperties"?: WaBubbleChart['initialReflectedProperties'];
  
  "internals"?: WaBubbleChart['internals'];

}

export type WaChartProps = {
  "label"?: WaChart['label'];
  
  "description"?: WaChart['description'];
  
  "type"?: WaChart['type'];
  
  "xLabel"?: WaChart['xLabel'];
  
  "yLabel"?: WaChart['yLabel'];
  
  "legend-position"?: WaChart['legendPosition'];
  
  "legendPosition"?: WaChart['legendPosition'];
  
  "stacked"?: WaChart['stacked'];
  
  "index-axis"?: WaChart['indexAxis'];
  
  "indexAxis"?: WaChart['indexAxis'];
  
  "grid"?: WaChart['grid'];
  
  "min"?: WaChart['min'];
  
  "max"?: WaChart['max'];
  
  "without-animation"?: WaChart['withoutAnimation'];
  
  "withoutAnimation"?: WaChart['withoutAnimation'];
  
  "without-legend"?: WaChart['withoutLegend'];
  
  "withoutLegend"?: WaChart['withoutLegend'];
  
  "without-tooltip"?: WaChart['withoutTooltip'];
  
  "withoutTooltip"?: WaChart['withoutTooltip'];
  
  "plugins"?: WaChart['plugins'];
  
  "dir"?: WaChart['dir'];
  
  "lang"?: WaChart['lang'];
  
  "did-ssr"?: WaChart['didSSR'];
  
  "didSSR"?: WaChart['didSSR'];
  
  "config"?: WaChart['config'];
  
  "chart"?: WaChart['chart'];
  
  "initialReflectedProperties"?: WaChart['initialReflectedProperties'];
  
  "internals"?: WaChart['internals'];

}

export type WaComboboxProps = {
  "name"?: WaCombobox['name'];
  
  "value"?: WaCombobox['value'];
  
  "size"?: WaCombobox['size'];
  
  "placeholder"?: WaCombobox['placeholder'];
  
  "multiple"?: WaCombobox['multiple'];
  
  "max-options-visible"?: WaCombobox['maxOptionsVisible'];
  
  "maxOptionsVisible"?: WaCombobox['maxOptionsVisible'];
  
  "disabled"?: WaCombobox['disabled'];
  
  "with-clear"?: WaCombobox['withClear'];
  
  "withClear"?: WaCombobox['withClear'];
  
  "open"?: WaCombobox['open'];
  
  "appearance"?: WaCombobox['appearance'];
  
  "pill"?: WaCombobox['pill'];
  
  "label"?: WaCombobox['label'];
  
  "placement"?: WaCombobox['placement'];
  
  "hint"?: WaCombobox['hint'];
  
  "with-label"?: WaCombobox['withLabel'];
  
  "withLabel"?: WaCombobox['withLabel'];
  
  "with-hint"?: WaCombobox['withHint'];
  
  "withHint"?: WaCombobox['withHint'];
  
  "required"?: WaCombobox['required'];
  
  "allow-custom-value"?: WaCombobox['allowCustomValue'];
  
  "allowCustomValue"?: WaCombobox['allowCustomValue'];
  
  "allow-create"?: WaCombobox['allowCreate'];
  
  "allowCreate"?: WaCombobox['allowCreate'];
  
  "autocapitalize"?: WaCombobox['autocapitalize'];
  
  "autocorrect"?: WaCombobox['autocorrect'];
  
  "inputmode"?: WaCombobox['inputmode'];
  
  "enterkeyhint"?: WaCombobox['enterkeyhint'];
  
  "spellcheck"?: WaCombobox['spellcheck'];
  
  "custom-error"?: WaCombobox['customError'];
  
  "customError"?: WaCombobox['customError'];
  
  "dir"?: WaCombobox['dir'];
  
  "lang"?: WaCombobox['lang'];
  
  "did-ssr"?: WaCombobox['didSSR'];
  
  "didSSR"?: WaCombobox['didSSR'];
  
  "assumeInteractionOn"?: WaCombobox['assumeInteractionOn'];
  
  "popup"?: WaCombobox['popup'];
  
  "combobox"?: WaCombobox['combobox'];
  
  "comboboxInput"?: WaCombobox['comboboxInput'];
  
  "valueInput"?: WaCombobox['valueInput'];
  
  "listbox"?: WaCombobox['listbox'];
  
  "liveRegion"?: WaCombobox['liveRegion'];
  
  "currentOption"?: WaCombobox['currentOption'];
  
  "selectedOptions"?: WaCombobox['selectedOptions'];
  
  "filteredOptions"?: WaCombobox['filteredOptions'];
  
  "inputValue"?: WaCombobox['inputValue'];
  
  "defaultValue"?: WaCombobox['defaultValue'];
  
  "filter"?: WaCombobox['filter'];
  
  "getTag"?: WaCombobox['getTag'];
  
  "input"?: WaCombobox['input'];
  
  "valueHasChanged"?: WaCombobox['valueHasChanged'];
  
  "hasInteracted"?: WaCombobox['hasInteracted'];
  
  "states"?: WaCombobox['states'];
  
  "emitInvalid"?: WaCombobox['emitInvalid'];
  
  "form"?: WaCombobox['form'];
  
  "initialReflectedProperties"?: WaCombobox['initialReflectedProperties'];
  
  "internals"?: WaCombobox['internals'];

  
  "oninput"?: (e: CustomEvent<InputEvent>) => void;
  
  "onchange"?: (e: CustomEvent<Event>) => void;
  
  "onfocus"?: (e: CustomEvent<never>) => void;
  
  "onblur"?: (e: CustomEvent<never>) => void;
  
  "onwa-clear"?: (e: CustomEvent<never>) => void;
  
  "onwa-show"?: (e: CustomEvent<never>) => void;
  
  "onwa-after-show"?: (e: CustomEvent<never>) => void;
  
  "onwa-hide"?: (e: CustomEvent<never>) => void;
  
  "onwa-after-hide"?: (e: CustomEvent<never>) => void;
  
  "onwa-create"?: (e: CustomEvent<never>) => void;
  
  "onwa-invalid"?: (e: CustomEvent<never>) => void;
}

export type WaDateInputProps = {
  "name"?: WaDateInput['name'];
  
  "value"?: WaDateInput['defaultValue'];
  
  "defaultValue"?: WaDateInput['defaultValue'];
  
  "disabled"?: WaDateInput['disabled'];
  
  "required"?: WaDateInput['required'];
  
  "readonly"?: WaDateInput['readonly'];
  
  "size"?: WaDateInput['size'];
  
  "appearance"?: WaDateInput['appearance'];
  
  "pill"?: WaDateInput['pill'];
  
  "label"?: WaDateInput['label'];
  
  "hint"?: WaDateInput['hint'];
  
  "autocomplete"?: WaDateInput['autocomplete'];
  
  "with-clear"?: WaDateInput['withClear'];
  
  "withClear"?: WaDateInput['withClear'];
  
  "with-label"?: WaDateInput['withLabel'];
  
  "withLabel"?: WaDateInput['withLabel'];
  
  "with-hint"?: WaDateInput['withHint'];
  
  "withHint"?: WaDateInput['withHint'];
  
  "mode"?: WaDateInput['mode'];
  
  "min"?: WaDateInput['min'];
  
  "max"?: WaDateInput['max'];
  
  "today"?: WaDateInput['today'];
  
  "first-day-of-week"?: WaDateInput['firstDayOfWeek'];
  
  "firstDayOfWeek"?: WaDateInput['firstDayOfWeek'];
  
  "disabled-dates"?: WaDateInput['disabledDates'];
  
  "disabledDates"?: WaDateInput['disabledDates'];
  
  "disabled-days-of-week"?: WaDateInput['disabledDaysOfWeek'];
  
  "disabledDaysOfWeek"?: WaDateInput['disabledDaysOfWeek'];
  
  "disable-past"?: WaDateInput['disablePast'];
  
  "disablePast"?: WaDateInput['disablePast'];
  
  "disable-future"?: WaDateInput['disableFuture'];
  
  "disableFuture"?: WaDateInput['disableFuture'];
  
  "min-range"?: WaDateInput['minRange'];
  
  "minRange"?: WaDateInput['minRange'];
  
  "max-range"?: WaDateInput['maxRange'];
  
  "maxRange"?: WaDateInput['maxRange'];
  
  "months"?: WaDateInput['months'];
  
  "page-by"?: WaDateInput['pageBy'];
  
  "pageBy"?: WaDateInput['pageBy'];
  
  "with-outside-days"?: WaDateInput['withOutsideDays'];
  
  "withOutsideDays"?: WaDateInput['withOutsideDays'];
  
  "with-week-numbers"?: WaDateInput['withWeekNumbers'];
  
  "withWeekNumbers"?: WaDateInput['withWeekNumbers'];
  
  "weekday-format"?: WaDateInput['weekdayFormat'];
  
  "weekdayFormat"?: WaDateInput['weekdayFormat'];
  
  "open"?: WaDateInput['open'];
  
  "placement"?: WaDateInput['placement'];
  
  "distance"?: WaDateInput['distance'];
  
  "custom-error"?: WaDateInput['customError'];
  
  "customError"?: WaDateInput['customError'];
  
  "dir"?: WaDateInput['dir'];
  
  "lang"?: WaDateInput['lang'];
  
  "did-ssr"?: WaDateInput['didSSR'];
  
  "didSSR"?: WaDateInput['didSSR'];
  
  "assumeInteractionOn"?: WaDateInput['assumeInteractionOn'];
  
  "popup"?: WaDateInput['popup'];
  
  "valueInput"?: WaDateInput['valueInput'];
  
  "inputGroup"?: WaDateInput['inputGroup'];
  
  "calendar"?: WaDateInput['calendar'];
  
  "isDateDisabled"?: WaDateInput['isDateDisabled'];
  
  "dayContent"?: WaDateInput['dayContent'];
  
  "input"?: WaDateInput['input'];
  
  "valueHasChanged"?: WaDateInput['valueHasChanged'];
  
  "hasInteracted"?: WaDateInput['hasInteracted'];
  
  "states"?: WaDateInput['states'];
  
  "emitInvalid"?: WaDateInput['emitInvalid'];
  
  "form"?: WaDateInput['form'];
  
  "initialReflectedProperties"?: WaDateInput['initialReflectedProperties'];
  
  "internals"?: WaDateInput['internals'];

  
  "oninput"?: (e: CustomEvent<InputEvent>) => void;
  
  "onchange"?: (e: CustomEvent<Event>) => void;
  
  "onfocus"?: (e: CustomEvent<never>) => void;
  
  "onblur"?: (e: CustomEvent<never>) => void;
  
  "onwa-clear"?: (e: CustomEvent<never>) => void;
  
  "onwa-show"?: (e: CustomEvent<never>) => void;
  
  "onwa-after-show"?: (e: CustomEvent<never>) => void;
  
  "onwa-hide"?: (e: CustomEvent<never>) => void;
  
  "onwa-after-hide"?: (e: CustomEvent<never>) => void;
  
  "onwa-invalid"?: (e: CustomEvent<never>) => void;
}

export type WaDatePickerProps = {
  "mode"?: WaDatePicker['mode'];
  
  "value"?: WaDatePicker['value'];
  
  "min"?: WaDatePicker['min'];
  
  "max"?: WaDatePicker['max'];
  
  "today"?: WaDatePicker['today'];
  
  "focused-date"?: WaDatePicker['focusedDate'];
  
  "focusedDate"?: WaDatePicker['focusedDate'];
  
  "view"?: WaDatePicker['view'];
  
  "months"?: WaDatePicker['months'];
  
  "page-by"?: WaDatePicker['pageBy'];
  
  "pageBy"?: WaDatePicker['pageBy'];
  
  "first-day-of-week"?: WaDatePicker['firstDayOfWeek'];
  
  "firstDayOfWeek"?: WaDatePicker['firstDayOfWeek'];
  
  "with-outside-days"?: WaDatePicker['withOutsideDays'];
  
  "withOutsideDays"?: WaDatePicker['withOutsideDays'];
  
  "with-week-numbers"?: WaDatePicker['withWeekNumbers'];
  
  "withWeekNumbers"?: WaDatePicker['withWeekNumbers'];
  
  "weekday-format"?: WaDatePicker['weekdayFormat'];
  
  "weekdayFormat"?: WaDatePicker['weekdayFormat'];
  
  "disabled"?: WaDatePicker['disabled'];
  
  "readonly"?: WaDatePicker['readonly'];
  
  "disabled-dates"?: WaDatePicker['disabledDates'];
  
  "disabledDates"?: WaDatePicker['disabledDates'];
  
  "disabled-days-of-week"?: WaDatePicker['disabledDaysOfWeek'];
  
  "disabledDaysOfWeek"?: WaDatePicker['disabledDaysOfWeek'];
  
  "disable-past"?: WaDatePicker['disablePast'];
  
  "disablePast"?: WaDatePicker['disablePast'];
  
  "disable-future"?: WaDatePicker['disableFuture'];
  
  "disableFuture"?: WaDatePicker['disableFuture'];
  
  "min-range"?: WaDatePicker['minRange'];
  
  "minRange"?: WaDatePicker['minRange'];
  
  "max-range"?: WaDatePicker['maxRange'];
  
  "maxRange"?: WaDatePicker['maxRange'];
  
  "size"?: WaDatePicker['size'];
  
  "locale"?: WaDatePicker['locale'];
  
  "dir"?: WaDatePicker['dir'];
  
  "lang"?: WaDatePicker['lang'];
  
  "did-ssr"?: WaDatePicker['didSSR'];
  
  "didSSR"?: WaDatePicker['didSSR'];
  
  "isDateDisabled"?: WaDatePicker['isDateDisabled'];
  
  "dayContent"?: WaDatePicker['dayContent'];
  
  "initialReflectedProperties"?: WaDatePicker['initialReflectedProperties'];
  
  "internals"?: WaDatePicker['internals'];

  
  "oninput"?: (e: CustomEvent<InputEvent>) => void;
  
  "onchange"?: (e: CustomEvent<Event>) => void;
  
  "onwa-focus-day"?: (e: CustomEvent<never>) => void;
  
  "onwa-view-change"?: (e: CustomEvent<never>) => void;
}

export type WaDoughnutChartProps = {
  "type"?: WaDoughnutChart['type'];
  
  "label"?: WaDoughnutChart['label'];
  
  "description"?: WaDoughnutChart['description'];
  
  "xLabel"?: WaDoughnutChart['xLabel'];
  
  "yLabel"?: WaDoughnutChart['yLabel'];
  
  "legend-position"?: WaDoughnutChart['legendPosition'];
  
  "legendPosition"?: WaDoughnutChart['legendPosition'];
  
  "stacked"?: WaDoughnutChart['stacked'];
  
  "index-axis"?: WaDoughnutChart['indexAxis'];
  
  "indexAxis"?: WaDoughnutChart['indexAxis'];
  
  "grid"?: WaDoughnutChart['grid'];
  
  "min"?: WaDoughnutChart['min'];
  
  "max"?: WaDoughnutChart['max'];
  
  "without-animation"?: WaDoughnutChart['withoutAnimation'];
  
  "withoutAnimation"?: WaDoughnutChart['withoutAnimation'];
  
  "without-legend"?: WaDoughnutChart['withoutLegend'];
  
  "withoutLegend"?: WaDoughnutChart['withoutLegend'];
  
  "without-tooltip"?: WaDoughnutChart['withoutTooltip'];
  
  "withoutTooltip"?: WaDoughnutChart['withoutTooltip'];
  
  "plugins"?: WaDoughnutChart['plugins'];
  
  "dir"?: WaDoughnutChart['dir'];
  
  "lang"?: WaDoughnutChart['lang'];
  
  "did-ssr"?: WaDoughnutChart['didSSR'];
  
  "didSSR"?: WaDoughnutChart['didSSR'];
  
  "config"?: WaDoughnutChart['config'];
  
  "chart"?: WaDoughnutChart['chart'];
  
  "initialReflectedProperties"?: WaDoughnutChart['initialReflectedProperties'];
  
  "internals"?: WaDoughnutChart['internals'];

}

export type WaFileInputProps = {
  "size"?: WaFileInput['size'];
  
  "label"?: WaFileInput['label'];
  
  "hint"?: WaFileInput['hint'];
  
  "multiple"?: WaFileInput['multiple'];
  
  "accept"?: WaFileInput['accept'];
  
  "required"?: WaFileInput['required'];
  
  "capture"?: WaFileInput['capture'];
  
  "with-label"?: WaFileInput['withLabel'];
  
  "withLabel"?: WaFileInput['withLabel'];
  
  "with-hint"?: WaFileInput['withHint'];
  
  "withHint"?: WaFileInput['withHint'];
  
  "name"?: WaFileInput['name'];
  
  "disabled"?: WaFileInput['disabled'];
  
  "custom-error"?: WaFileInput['customError'];
  
  "customError"?: WaFileInput['customError'];
  
  "dir"?: WaFileInput['dir'];
  
  "lang"?: WaFileInput['lang'];
  
  "did-ssr"?: WaFileInput['didSSR'];
  
  "didSSR"?: WaFileInput['didSSR'];
  
  "assumeInteractionOn"?: WaFileInput['assumeInteractionOn'];
  
  "dropzone"?: WaFileInput['dropzone'];
  
  "input"?: WaFileInput['input'];
  
  "files"?: WaFileInput['files'];
  
  "dragging"?: WaFileInput['dragging'];
  
  "valueHasChanged"?: WaFileInput['valueHasChanged'];
  
  "hasInteracted"?: WaFileInput['hasInteracted'];
  
  "states"?: WaFileInput['states'];
  
  "emitInvalid"?: WaFileInput['emitInvalid'];
  
  "form"?: WaFileInput['form'];
  
  "initialReflectedProperties"?: WaFileInput['initialReflectedProperties'];
  
  "internals"?: WaFileInput['internals'];

  
  "oninput"?: (e: CustomEvent<Event>) => void;
  
  "onchange"?: (e: CustomEvent<Event>) => void;
  
  "onfocus"?: (e: CustomEvent<never>) => void;
  
  "onblur"?: (e: CustomEvent<never>) => void;
  
  "onwa-invalid"?: (e: CustomEvent<never>) => void;
}

export type WaLineChartProps = {
  "type"?: WaLineChart['type'];
  
  "label"?: WaLineChart['label'];
  
  "description"?: WaLineChart['description'];
  
  "xLabel"?: WaLineChart['xLabel'];
  
  "yLabel"?: WaLineChart['yLabel'];
  
  "legend-position"?: WaLineChart['legendPosition'];
  
  "legendPosition"?: WaLineChart['legendPosition'];
  
  "stacked"?: WaLineChart['stacked'];
  
  "index-axis"?: WaLineChart['indexAxis'];
  
  "indexAxis"?: WaLineChart['indexAxis'];
  
  "grid"?: WaLineChart['grid'];
  
  "min"?: WaLineChart['min'];
  
  "max"?: WaLineChart['max'];
  
  "without-animation"?: WaLineChart['withoutAnimation'];
  
  "withoutAnimation"?: WaLineChart['withoutAnimation'];
  
  "without-legend"?: WaLineChart['withoutLegend'];
  
  "withoutLegend"?: WaLineChart['withoutLegend'];
  
  "without-tooltip"?: WaLineChart['withoutTooltip'];
  
  "withoutTooltip"?: WaLineChart['withoutTooltip'];
  
  "plugins"?: WaLineChart['plugins'];
  
  "dir"?: WaLineChart['dir'];
  
  "lang"?: WaLineChart['lang'];
  
  "did-ssr"?: WaLineChart['didSSR'];
  
  "didSSR"?: WaLineChart['didSSR'];
  
  "config"?: WaLineChart['config'];
  
  "chart"?: WaLineChart['chart'];
  
  "initialReflectedProperties"?: WaLineChart['initialReflectedProperties'];
  
  "internals"?: WaLineChart['internals'];

}

export type WaNumberInputProps = {
  "title"?: WaNumberInput['title'];
  
  "value"?: WaNumberInput['defaultValue'];
  
  "defaultValue"?: WaNumberInput['defaultValue'];
  
  "size"?: WaNumberInput['size'];
  
  "appearance"?: WaNumberInput['appearance'];
  
  "pill"?: WaNumberInput['pill'];
  
  "label"?: WaNumberInput['label'];
  
  "hint"?: WaNumberInput['hint'];
  
  "placeholder"?: WaNumberInput['placeholder'];
  
  "readonly"?: WaNumberInput['readonly'];
  
  "required"?: WaNumberInput['required'];
  
  "min"?: WaNumberInput['min'];
  
  "max"?: WaNumberInput['max'];
  
  "step"?: WaNumberInput['step'];
  
  "without-steppers"?: WaNumberInput['withoutSteppers'];
  
  "withoutSteppers"?: WaNumberInput['withoutSteppers'];
  
  "autocomplete"?: WaNumberInput['autocomplete'];
  
  "autofocus"?: WaNumberInput['autofocus'];
  
  "enterkeyhint"?: WaNumberInput['enterkeyhint'];
  
  "inputmode"?: WaNumberInput['inputmode'];
  
  "with-label"?: WaNumberInput['withLabel'];
  
  "withLabel"?: WaNumberInput['withLabel'];
  
  "with-hint"?: WaNumberInput['withHint'];
  
  "withHint"?: WaNumberInput['withHint'];
  
  "name"?: WaNumberInput['name'];
  
  "disabled"?: WaNumberInput['disabled'];
  
  "custom-error"?: WaNumberInput['customError'];
  
  "customError"?: WaNumberInput['customError'];
  
  "dir"?: WaNumberInput['dir'];
  
  "lang"?: WaNumberInput['lang'];
  
  "did-ssr"?: WaNumberInput['didSSR'];
  
  "didSSR"?: WaNumberInput['didSSR'];
  
  "assumeInteractionOn"?: WaNumberInput['assumeInteractionOn'];
  
  "input"?: WaNumberInput['input'];
  
  "valueHasChanged"?: WaNumberInput['valueHasChanged'];
  
  "hasInteracted"?: WaNumberInput['hasInteracted'];
  
  "states"?: WaNumberInput['states'];
  
  "emitInvalid"?: WaNumberInput['emitInvalid'];
  
  "form"?: WaNumberInput['form'];
  
  "initialReflectedProperties"?: WaNumberInput['initialReflectedProperties'];
  
  "internals"?: WaNumberInput['internals'];

  
  "oninput"?: (e: CustomEvent<InputEvent>) => void;
  
  "onchange"?: (e: CustomEvent<Event>) => void;
  
  "onblur"?: (e: CustomEvent<never>) => void;
  
  "onfocus"?: (e: CustomEvent<never>) => void;
  
  "onbeforeinput"?: (e: CustomEvent<never>) => void;
  
  "onwa-invalid"?: (e: CustomEvent<never>) => void;
}

export type WaPieChartProps = {
  "type"?: WaPieChart['type'];
  
  "label"?: WaPieChart['label'];
  
  "description"?: WaPieChart['description'];
  
  "xLabel"?: WaPieChart['xLabel'];
  
  "yLabel"?: WaPieChart['yLabel'];
  
  "legend-position"?: WaPieChart['legendPosition'];
  
  "legendPosition"?: WaPieChart['legendPosition'];
  
  "stacked"?: WaPieChart['stacked'];
  
  "index-axis"?: WaPieChart['indexAxis'];
  
  "indexAxis"?: WaPieChart['indexAxis'];
  
  "grid"?: WaPieChart['grid'];
  
  "min"?: WaPieChart['min'];
  
  "max"?: WaPieChart['max'];
  
  "without-animation"?: WaPieChart['withoutAnimation'];
  
  "withoutAnimation"?: WaPieChart['withoutAnimation'];
  
  "without-legend"?: WaPieChart['withoutLegend'];
  
  "withoutLegend"?: WaPieChart['withoutLegend'];
  
  "without-tooltip"?: WaPieChart['withoutTooltip'];
  
  "withoutTooltip"?: WaPieChart['withoutTooltip'];
  
  "plugins"?: WaPieChart['plugins'];
  
  "dir"?: WaPieChart['dir'];
  
  "lang"?: WaPieChart['lang'];
  
  "did-ssr"?: WaPieChart['didSSR'];
  
  "didSSR"?: WaPieChart['didSSR'];
  
  "config"?: WaPieChart['config'];
  
  "chart"?: WaPieChart['chart'];
  
  "initialReflectedProperties"?: WaPieChart['initialReflectedProperties'];
  
  "internals"?: WaPieChart['internals'];

}

export type WaPolarAreaChartProps = {
  "type"?: WaPolarAreaChart['type'];
  
  "label"?: WaPolarAreaChart['label'];
  
  "description"?: WaPolarAreaChart['description'];
  
  "xLabel"?: WaPolarAreaChart['xLabel'];
  
  "yLabel"?: WaPolarAreaChart['yLabel'];
  
  "legend-position"?: WaPolarAreaChart['legendPosition'];
  
  "legendPosition"?: WaPolarAreaChart['legendPosition'];
  
  "stacked"?: WaPolarAreaChart['stacked'];
  
  "index-axis"?: WaPolarAreaChart['indexAxis'];
  
  "indexAxis"?: WaPolarAreaChart['indexAxis'];
  
  "grid"?: WaPolarAreaChart['grid'];
  
  "min"?: WaPolarAreaChart['min'];
  
  "max"?: WaPolarAreaChart['max'];
  
  "without-animation"?: WaPolarAreaChart['withoutAnimation'];
  
  "withoutAnimation"?: WaPolarAreaChart['withoutAnimation'];
  
  "without-legend"?: WaPolarAreaChart['withoutLegend'];
  
  "withoutLegend"?: WaPolarAreaChart['withoutLegend'];
  
  "without-tooltip"?: WaPolarAreaChart['withoutTooltip'];
  
  "withoutTooltip"?: WaPolarAreaChart['withoutTooltip'];
  
  "plugins"?: WaPolarAreaChart['plugins'];
  
  "dir"?: WaPolarAreaChart['dir'];
  
  "lang"?: WaPolarAreaChart['lang'];
  
  "did-ssr"?: WaPolarAreaChart['didSSR'];
  
  "didSSR"?: WaPolarAreaChart['didSSR'];
  
  "config"?: WaPolarAreaChart['config'];
  
  "chart"?: WaPolarAreaChart['chart'];
  
  "initialReflectedProperties"?: WaPolarAreaChart['initialReflectedProperties'];
  
  "internals"?: WaPolarAreaChart['internals'];

}

export type WaRadarChartProps = {
  "type"?: WaRadarChart['type'];
  
  "label"?: WaRadarChart['label'];
  
  "description"?: WaRadarChart['description'];
  
  "xLabel"?: WaRadarChart['xLabel'];
  
  "yLabel"?: WaRadarChart['yLabel'];
  
  "legend-position"?: WaRadarChart['legendPosition'];
  
  "legendPosition"?: WaRadarChart['legendPosition'];
  
  "stacked"?: WaRadarChart['stacked'];
  
  "index-axis"?: WaRadarChart['indexAxis'];
  
  "indexAxis"?: WaRadarChart['indexAxis'];
  
  "grid"?: WaRadarChart['grid'];
  
  "min"?: WaRadarChart['min'];
  
  "max"?: WaRadarChart['max'];
  
  "without-animation"?: WaRadarChart['withoutAnimation'];
  
  "withoutAnimation"?: WaRadarChart['withoutAnimation'];
  
  "without-legend"?: WaRadarChart['withoutLegend'];
  
  "withoutLegend"?: WaRadarChart['withoutLegend'];
  
  "without-tooltip"?: WaRadarChart['withoutTooltip'];
  
  "withoutTooltip"?: WaRadarChart['withoutTooltip'];
  
  "plugins"?: WaRadarChart['plugins'];
  
  "dir"?: WaRadarChart['dir'];
  
  "lang"?: WaRadarChart['lang'];
  
  "did-ssr"?: WaRadarChart['didSSR'];
  
  "didSSR"?: WaRadarChart['didSSR'];
  
  "config"?: WaRadarChart['config'];
  
  "chart"?: WaRadarChart['chart'];
  
  "initialReflectedProperties"?: WaRadarChart['initialReflectedProperties'];
  
  "internals"?: WaRadarChart['internals'];

}

export type WaScatterChartProps = {
  "type"?: WaScatterChart['type'];
  
  "label"?: WaScatterChart['label'];
  
  "description"?: WaScatterChart['description'];
  
  "xLabel"?: WaScatterChart['xLabel'];
  
  "yLabel"?: WaScatterChart['yLabel'];
  
  "legend-position"?: WaScatterChart['legendPosition'];
  
  "legendPosition"?: WaScatterChart['legendPosition'];
  
  "stacked"?: WaScatterChart['stacked'];
  
  "index-axis"?: WaScatterChart['indexAxis'];
  
  "indexAxis"?: WaScatterChart['indexAxis'];
  
  "grid"?: WaScatterChart['grid'];
  
  "min"?: WaScatterChart['min'];
  
  "max"?: WaScatterChart['max'];
  
  "without-animation"?: WaScatterChart['withoutAnimation'];
  
  "withoutAnimation"?: WaScatterChart['withoutAnimation'];
  
  "without-legend"?: WaScatterChart['withoutLegend'];
  
  "withoutLegend"?: WaScatterChart['withoutLegend'];
  
  "without-tooltip"?: WaScatterChart['withoutTooltip'];
  
  "withoutTooltip"?: WaScatterChart['withoutTooltip'];
  
  "plugins"?: WaScatterChart['plugins'];
  
  "dir"?: WaScatterChart['dir'];
  
  "lang"?: WaScatterChart['lang'];
  
  "did-ssr"?: WaScatterChart['didSSR'];
  
  "didSSR"?: WaScatterChart['didSSR'];
  
  "config"?: WaScatterChart['config'];
  
  "chart"?: WaScatterChart['chart'];
  
  "initialReflectedProperties"?: WaScatterChart['initialReflectedProperties'];
  
  "internals"?: WaScatterChart['internals'];

}

export type WaSparklineProps = {
  "label"?: WaSparkline['label'];
  
  "data"?: WaSparkline['data'];
  
  "appearance"?: WaSparkline['appearance'];
  
  "trend"?: WaSparkline['trend'];
  
  "curve"?: WaSparkline['curve'];
  
  "dir"?: WaSparkline['dir'];
  
  "lang"?: WaSparkline['lang'];
  
  "did-ssr"?: WaSparkline['didSSR'];
  
  "didSSR"?: WaSparkline['didSSR'];
  
  "initialReflectedProperties"?: WaSparkline['initialReflectedProperties'];
  
  "internals"?: WaSparkline['internals'];

}

export type WaToastItemProps = {
  "variant"?: WaToastItem['variant'];
  
  "size"?: WaToastItem['size'];
  
  "duration"?: WaToastItem['duration'];
  
  "with-icon"?: WaToastItem['withIcon'];
  
  "withIcon"?: WaToastItem['withIcon'];
  
  "dir"?: WaToastItem['dir'];
  
  "lang"?: WaToastItem['lang'];
  
  "did-ssr"?: WaToastItem['didSSR'];
  
  "didSSR"?: WaToastItem['didSSR'];
  
  "toastItemElement"?: WaToastItem['toastItemElement'];
  
  "initialReflectedProperties"?: WaToastItem['initialReflectedProperties'];
  
  "internals"?: WaToastItem['internals'];

  
  "onwa-show"?: (e: CustomEvent<never>) => void;
  
  "onwa-after-show"?: (e: CustomEvent<never>) => void;
  
  "onwa-hide"?: (e: CustomEvent<never>) => void;
  
  "onwa-after-hide"?: (e: CustomEvent<never>) => void;
}

export type WaToastProps = {
  "placement"?: WaToast['placement'];
  
  "dir"?: WaToast['dir'];
  
  "lang"?: WaToast['lang'];
  
  "did-ssr"?: WaToast['didSSR'];
  
  "didSSR"?: WaToast['didSSR'];
  
  "stack"?: WaToast['stack'];
  
  "initialReflectedProperties"?: WaToast['initialReflectedProperties'];
  
  "internals"?: WaToast['internals'];

}

export type WaVideoPlaylistProps = {
  "controls"?: WaVideoPlaylist['controls'];
  
  "icon-library"?: WaVideoPlaylist['iconLibrary'];
  
  "iconLibrary"?: WaVideoPlaylist['iconLibrary'];
  
  "dir"?: WaVideoPlaylist['dir'];
  
  "lang"?: WaVideoPlaylist['lang'];
  
  "did-ssr"?: WaVideoPlaylist['didSSR'];
  
  "didSSR"?: WaVideoPlaylist['didSSR'];
  
  "initialReflectedProperties"?: WaVideoPlaylist['initialReflectedProperties'];
  
  "internals"?: WaVideoPlaylist['internals'];

  
  "onwa-video-change"?: (e: CustomEvent<never>) => void;
}

export type WaVideoProps = {
  "controls"?: WaVideo['controls'];
  
  "thumbnails"?: WaVideo['thumbnails'];
  
  "src"?: WaVideo['src'];
  
  "poster"?: WaVideo['poster'];
  
  "title"?: WaVideo['title'];
  
  "playing"?: WaVideo['playing'];
  
  "muted"?: WaVideo['muted'];
  
  "volume"?: WaVideo['volume'];
  
  "duration"?: WaVideo['duration'];
  
  "currentTime"?: WaVideo['currentTime'];
  
  "autoplay"?: WaVideo['autoplay'];
  
  "loop"?: WaVideo['loop'];
  
  "autoplay-muted"?: WaVideo['autoplayMuted'];
  
  "autoplayMuted"?: WaVideo['autoplayMuted'];
  
  "autoplay-on-visible"?: WaVideo['autoplayOnVisible'];
  
  "autoplayOnVisible"?: WaVideo['autoplayOnVisible'];
  
  "preload"?: WaVideo['preload'];
  
  "icon-library"?: WaVideo['iconLibrary'];
  
  "iconLibrary"?: WaVideo['iconLibrary'];
  
  "dir"?: WaVideo['dir'];
  
  "lang"?: WaVideo['lang'];
  
  "did-ssr"?: WaVideo['didSSR'];
  
  "didSSR"?: WaVideo['didSSR'];
  
  "initialReflectedProperties"?: WaVideo['initialReflectedProperties'];
  
  "internals"?: WaVideo['internals'];

  
  "ontimeupdate"?: (e: CustomEvent<Event>) => void;
  
  "onplay"?: (e: CustomEvent<never>) => void;
  
  "onpause"?: (e: CustomEvent<never>) => void;
  
  "onvolumechange"?: (e: CustomEvent<never>) => void;
  
  "onerror"?: (e: CustomEvent<never>) => void;
  
  "onended"?: (e: CustomEvent<never>) => void;
  
  "onloadedmetadata"?: (e: CustomEvent<never>) => void;
}

type BaseProps<T extends HTMLElement> = {
  children?: any;
  class?: string;
  className?: string;
  ref?: T | ((e: T) => void);
  slot?: string;
  style?: any;
  [key: string]: any;
};

type BaseEvents = Record<string, ((e: any) => void) | undefined>;

interface WaProIntrinsicElements {
  'wa-bar-chart': Partial<WaBarChartProps & BaseProps<WaBarChart> & BaseEvents>;
  'wa-bubble-chart': Partial<WaBubbleChartProps & BaseProps<WaBubbleChart> & BaseEvents>;
  'wa-chart': Partial<WaChartProps & BaseProps<WaChart> & BaseEvents>;
  'wa-combobox': Partial<WaComboboxProps & BaseProps<WaCombobox> & BaseEvents>;
  'wa-date-input': Partial<WaDateInputProps & BaseProps<WaDateInput> & BaseEvents>;
  'wa-date-picker': Partial<WaDatePickerProps & BaseProps<WaDatePicker> & BaseEvents>;
  'wa-doughnut-chart': Partial<WaDoughnutChartProps & BaseProps<WaDoughnutChart> & BaseEvents>;
  'wa-file-input': Partial<WaFileInputProps & BaseProps<WaFileInput> & BaseEvents>;
  'wa-line-chart': Partial<WaLineChartProps & BaseProps<WaLineChart> & BaseEvents>;
  'wa-number-input': Partial<WaNumberInputProps & BaseProps<WaNumberInput> & BaseEvents>;
  'wa-pie-chart': Partial<WaPieChartProps & BaseProps<WaPieChart> & BaseEvents>;
  'wa-polar-area-chart': Partial<WaPolarAreaChartProps & BaseProps<WaPolarAreaChart> & BaseEvents>;
  'wa-radar-chart': Partial<WaRadarChartProps & BaseProps<WaRadarChart> & BaseEvents>;
  'wa-scatter-chart': Partial<WaScatterChartProps & BaseProps<WaScatterChart> & BaseEvents>;
  'wa-sparkline': Partial<WaSparklineProps & BaseProps<WaSparkline> & BaseEvents>;
  'wa-toast': Partial<WaToastProps & BaseProps<WaToast> & BaseEvents>;
  'wa-toast-item': Partial<WaToastItemProps & BaseProps<WaToastItem> & BaseEvents>;
  'wa-video': Partial<WaVideoProps & BaseProps<WaVideo> & BaseEvents>;
  'wa-video-playlist': Partial<WaVideoPlaylistProps & BaseProps<WaVideoPlaylist> & BaseEvents>;
}

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements extends WaProIntrinsicElements {}
  }
}

declare global {
  namespace JSX {
    interface IntrinsicElements extends WaProIntrinsicElements {}
  }
}

export {};
