/**
 * Regenerate Utilities
 *
 * PURPOSE: Regenerates auto-generated files (kigumi.ts, layers.css, theme.css, vite-env.d.ts)
 * when configuration changes.
 *
 * EXPORTS:
 * - regenerateKigumiSetup() - Regenerate kigumi.ts + layers.css with theme config
 * - generateLayersCSS() - Generate layers.css with @layer cascade control
 * - surgicalRewriteLayersCss() - Rewrite only the Web Awesome @import lines in
 *   an existing layers.css, preserving user customizations
 * - generateViteEnvDts() - Generate TypeScript declarations for wa-* elements
 * - generateThemeCSS() - Generate theme.css content
 * - generateGitIgnore() - Create/update .gitignore
 *
 * @see AGENTS.md for auto-generated files list
 */

import fs from 'fs-extra';
import path from 'path';
import {
  WEB_AWESOME_FREE_PACKAGE,
  WEB_AWESOME_PRO_PACKAGE,
} from '../constants.js';
import type { KigumiConfig } from '../schemas/config.js';
import type { Tier } from './tier.js';
import { detectTierSync, getWebAwesomePackage } from './tier.js';
import {
  isNextProject,
  detectNextRouter,
  type NextRouter,
} from './detect-framework.js';
import { toKigumiAlias } from './project-config.js';
import { LayersCssRewriteError } from '../errors/layers-css.js';

export interface RegenerateOptions {
  /** Skip regenerating layers.css if it exists (for init command) */
  preserveLayersCSS?: boolean;
}

/**
 * Regenerate the Kigumi setup file with updated theme configuration
 *
 * This function is used by init and all theme management commands
 * to ensure kigumi.ts and layers.css are always in sync with the config.
 *
 * @param cwd - Current working directory
 * @param config - Kigumi configuration
 * @param utilsDir - Path to utils directory (e.g., 'src/lib')
 * @param tierOverride - Optional tier override (uses .env detection if not provided)
 * @param options - Optional regeneration options
 * @param isNextOverride - Pre-resolved Next-project flag. Callers that
 *   already detected this at the command entry should pass it through so
 *   the setup regeneration does not repeat the filesystem probe.
 * @param nextRouterOverride - Pre-resolved Next router. Same contract.
 * @returns Object indicating if layers.css was preserved
 */
export async function regenerateKigumiSetup(
  cwd: string,
  config: KigumiConfig,
  utilsDir: string,
  tierOverride?: Tier,
  options?: RegenerateOptions,
  isNextOverride?: boolean,
  nextRouterOverride?: NextRouter
): Promise<{ layersPreserved: boolean }> {
  // Detect tier from .env, or use override
  const tier = tierOverride || detectTierSync(cwd);
  const packageName = getWebAwesomePackage(tier);
  const stylesDir = config.stylesDir || 'src/styles';
  const stylesAlias = toKigumiAlias(stylesDir);

  // Pages Router rejects side-effect global CSS imports from any file other
  // than `pages/_app.tsx`, including transitively via `lib/kigumi.ts`. Skip
  // the `layers.css` import in that case; the user adds it directly in
  // `_app.tsx` (post-install instructions + Upgrading guide spell this out).
  // Prefer caller-provided context so init/add/update sweeps skip the probe.
  //
  // Resolved up-front because `generateLayersCSS` also branches on
  // `nextRouter` (see F-038: the `layer(…)` qualifier on `@import` is not
  // preserved by Pages Router's Webpack postcss-import pass).
  const isNext = isNextOverride ?? (await isNextProject(cwd));
  const nextRouter = isNext
    ? (nextRouterOverride ?? (await detectNextRouter(cwd)))
    : undefined;
  const skipLayersImport = nextRouter === 'pages';

  // Check if layers.css exists and should be preserved
  const layersPath = path.join(cwd, stylesDir, 'layers.css');
  const layersExists = await fs.pathExists(layersPath);
  let layersPreserved = false;

  if (options?.preserveLayersCSS && layersExists) {
    layersPreserved = true;
  } else {
    // Generate layers.css
    const isCommunityTheme =
      config.installedThemes?.[config.theme.selected]?.source === 'community';
    const layersContent = await generateLayersCSS(
      packageName,
      config.theme.selected,
      stylesDir,
      isCommunityTheme,
      nextRouter
    );
    await fs.writeFile(layersPath, layersContent);
  }

  // Generate theme classes script
  const themeClasses =
    config.theme.selected !== 'none' ? generateThemeClassesScript(config) : '';

  const layersImportLine = skipLayersImport
    ? `// Pages Router: layers.css must be imported from pages/_app.tsx
// directly — Next forbids global CSS imports from lib/.`
    : `import '${stylesAlias}/layers.css';`;

  // Generate kigumi.ts that imports layers.css (except in Pages Router)
  const setupFileContent = `/**
 * Kigumi Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports Web Awesome styles with cascade layers and applies theme classes.
 *
 * Current theme: ${config.theme.selected}
 * Current palette: ${config.theme.palette}
 * Current brand: ${config.theme.brandColor}
 *
 * To change themes, use: kigumi theme <name>
 * To change brand color, use: kigumi brand <color>
 */

// Prevent duplicate custom-element registrations when Web Awesome components
// share internal dependencies (e.g. toast-item internally uses progress-ring)
if (typeof customElements !== 'undefined') {
  const _ceDefine = customElements.define.bind(customElements);
  customElements.define = function (name: string, ctor: CustomElementConstructor, options?: ElementDefinitionOptions) {
    if (!customElements.get(name)) _ceDefine(name, ctor, options);
  };
}

// Import Web Awesome CSS with cascade layers for predictable specificity control
${layersImportLine}
${themeClasses}
export {};
`;

  // Next.js App Router: kigumi.ts patches `customElements.define`, which only
  // exists in the browser. Mark it as a Client Module so the patch runs on the
  // client; the existing `typeof customElements !== 'undefined'` guard makes
  // the SSR pass a no-op.
  const finalSetupFileContent = isNext
    ? `'use client';\n\n${setupFileContent}`
    : setupFileContent;

  const setupFilePath = path.join(cwd, utilsDir, 'kigumi.ts');
  await fs.writeFile(setupFilePath, finalSetupFileContent);

  return { layersPreserved };
}

/**
 * Generate theme classes script for kigumi.ts
 * @internal
 */
function generateThemeClassesScript(config: KigumiConfig): string {
  return `
// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\\bwa-theme-\\S+/g, '')
    .replace(/\\bwa-palette-\\S+/g, '')
    .replace(/\\bwa-brand-\\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-${config.theme.selected}');
  html.classList.add('wa-palette-${config.theme.palette}');
  html.classList.add('wa-brand-${config.theme.brandColor}');
}
`;
}

/**
 * Generate layers.css with @layer imports
 *
 * This file wraps Web Awesome CSS imports in cascade layers for predictable
 * specificity control. Generated by CLI alongside kigumi.ts.
 *
 * @param packageName - Web Awesome package name (e.g., '@awesome.me/webawesome-pro')
 * @param themeName - Selected theme name (e.g., 'tailspin')
 * @param stylesDir - Styles directory path (e.g., 'src/styles')
 * @param isCommunityTheme - Whether the selected theme is a community theme
 * @param nextRouter - Next.js router flavor (drives the F-038 Pages Router branch)
 * @returns CSS content string
 */
export async function generateLayersCSS(
  packageName: string,
  themeName: string,
  _stylesDir: string,
  isCommunityTheme = false,
  nextRouter?: NextRouter
): Promise<string> {
  // Community themes are stored locally (sibling of layers.css); built-in
  // themes come from the WA package. Use relative paths inside layers.css
  // so the `@/` alias is not required for CSS resolution — Next Pages Router
  // and some bundler configurations don't resolve tsconfig paths inside CSS
  // `@import` statements.
  const themeImport = isCommunityTheme
    ? `./community-themes/${themeName}.css`
    : `${packageName}/dist/styles/themes/${themeName}.css`;

  // F-038: Next.js Pages Router runs CSS through Webpack's `next-css-loader`
  // + `postcss-import`, which drops the whole `@import … layer(…)` line
  // when it inlines the chain (not just the qualifier). The theme file never
  // lands in the bundle, so `--wa-color-brand-*` / `--wa-font-family-*` are
  // empty at `:root`. Emit plain `@import` statements on that path so Webpack
  // accepts them. WA rules then load as *unlayered* styles, which in the CSS
  // cascade outrank any named layer. That's fine for the stock `theme.css`
  // template (plain `:root { --wa-* }` overrides win via source order), but
  // it does mean a user who wraps overrides in `@layer theme { … }` on Pages
  // Router will lose to WA's unlayered rules. The `@layer base, theme;`
  // declaration still emits so any named-layer authoring the user adds keeps
  // `base < theme` order relative to other named layers.
  // App Router (Turbopack) and Vite both preserve the qualifier.
  const usePlainImports = nextRouter === 'pages';
  const baseLayer = usePlainImports ? '' : ' layer(base)';
  const themeLayer = usePlainImports ? '' : ' layer(theme)';

  return `/**
 * Web Awesome CSS Cascade Layers
 *
 * This file is auto-generated by Kigumi CLI.
 * It wraps Web Awesome CSS in cascade layers for predictable specificity control.
 *
 * Layer hierarchy (earlier = lower priority):
 * 1. base - Web Awesome foundation + theme styles
 * 2. theme - Your custom CSS overrides (theme.css)
 *
 * Learn more: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
 */

/* Define layer order */
@layer base, theme;

/* Layer 1: Web Awesome base styles */
@import '${packageName}/dist/styles/webawesome.css'${baseLayer};

/* Layer 1: Web Awesome theme styles */
@import '${themeImport}'${baseLayer};

/* Layer 2: Your custom CSS overrides (sibling of layers.css) */
@import './theme.css'${themeLayer};
`;
}

/**
 * Surgically rewrite the Web Awesome package reference in an existing
 * `layers.css`, preserving all other content.
 *
 * This is used during tier migration (free -> pro or pro -> free) and
 * by `kigumi doctor` to repair a stale `layers.css` where the CSS
 * `@import` statements still point at the previously-installed package.
 *
 * The function uses two regex patterns to locate only the Web Awesome
 * `@import` lines:
 *
 *   @import '<package>/dist/styles/webawesome.css' ...
 *   @import '<package>/dist/styles/themes/<theme>.css' ...
 *
 * Everything else in the file (user `@layer` declarations, comments,
 * custom imports, theme.css imports) is left verbatim.
 *
 * If neither regex matches, the user has restructured the file beyond
 * what we can safely patch, and the function throws `LayersCssRewriteError`
 * with an actionable manual fix message.
 *
 * Idempotent: returns `{ changed: false }` when the file already imports
 * from `targetPackage` so repeated runs are safe.
 *
 * @param filePath - Absolute path to the layers.css file
 * @param targetPackage - Either WEB_AWESOME_FREE_PACKAGE or WEB_AWESOME_PRO_PACKAGE
 * @param themeName - The current theme name (used for the error message's manual-fix instructions)
 * @throws LayersCssRewriteError if the expected @import pattern is missing
 */
export async function surgicalRewriteLayersCss(
  filePath: string,
  targetPackage: string,
  themeName: string
): Promise<{ changed: boolean }> {
  const content = await fs.readFile(filePath, 'utf-8');

  // Match `@import '<package>/dist/styles/webawesome.css'` where <package>
  // is either the free or pro Web Awesome package. Captures the package
  // name so we can swap it.
  //
  // Using a non-global regex for `.test()` but constructing a global one
  // for `.replace()` so we can handle the (unusual but possible) case of
  // multiple occurrences.
  const basePattern =
    /@import\s+['"](@awesome\.me\/webawesome(?:-pro)?)\/dist\/styles\/webawesome\.css['"]/;
  const basePatternGlobal = new RegExp(basePattern.source, 'g');

  const themePattern =
    /@import\s+['"](@awesome\.me\/webawesome(?:-pro)?)\/dist\/styles\/themes\/([a-z][a-z0-9-]*)\.css['"]/;
  const themePatternGlobal = new RegExp(themePattern.source, 'g');

  const hasBase = basePattern.test(content);
  const hasTheme = themePattern.test(content);

  if (!hasBase && !hasTheme) {
    // File has been restructured beyond recognition. Figure out which
    // package it currently references (if any) so the error message can
    // suggest the correct direction.
    const currentPackage = content.includes(WEB_AWESOME_PRO_PACKAGE)
      ? WEB_AWESOME_PRO_PACKAGE
      : WEB_AWESOME_FREE_PACKAGE;

    throw new LayersCssRewriteError(
      filePath,
      currentPackage,
      targetPackage,
      themeName
    );
  }

  let next = content;

  if (hasBase) {
    next = next.replace(
      basePatternGlobal,
      `@import '${targetPackage}/dist/styles/webawesome.css'`
    );
  }

  if (hasTheme) {
    next = next.replace(
      themePatternGlobal,
      (_match, _pkg, theme) =>
        `@import '${targetPackage}/dist/styles/themes/${theme}.css'`
    );
  }

  if (next === content) {
    // Already in the target state. Nothing to do.
    return { changed: false };
  }

  await fs.writeFile(filePath, next);
  return { changed: true };
}

/**
 * Generate vite-env.d.ts with Web Awesome custom element type definitions
 *
 * This file extends React's JSX.IntrinsicElements to include wa-* custom elements,
 * using the official types from the Web Awesome package.
 *
 * See: https://webawesome.com/docs/#react-users
 *
 * @param cwd - Current working directory
 * @param srcDir - Source directory (e.g., 'src')
 * @param waPackage - Web Awesome package name (defaults to free package)
 */
export async function generateViteEnvDts(
  cwd: string,
  srcDir: string,
  waPackage: string = WEB_AWESOME_FREE_PACKAGE
): Promise<void> {
  const viteEnvContent = `/// <reference types="vite/client" />

/**
 * Web Awesome JSX Types
 *
 * This extends React's JSX.IntrinsicElements with Web Awesome custom elements.
 * Uses the official types from the ${waPackage} package.
 *
 * IMPORTANT: Uses 'declare global' to extend JSX without overwriting React module.
 *
 * @see https://webawesome.com/docs/#react-users
 */

import type {
  CustomElements,
  CustomCssProperties,
} from '${waPackage}/dist/custom-elements-jsx.d.ts';

declare global {
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    interface IntrinsicElements extends CustomElements {}
  }
}

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface CSSProperties extends CustomCssProperties {}
}

export {};
`;

  const viteEnvPath = path.join(cwd, srcDir, 'vite-env.d.ts');
  await fs.writeFile(viteEnvPath, viteEnvContent);
}

/**
 * Generate web-awesome.d.ts for Next.js projects
 *
 * Same Web Awesome JSX typings as the Vite flavor, but without the
 * `/// <reference types="vite/client" />` directive (Next owns its own
 * `next-env.d.ts`). Written to `<srcDir>/web-awesome.d.ts` so it lives
 * next to the rest of the app's TypeScript.
 *
 * @param cwd - Current working directory
 * @param srcDir - Source directory (e.g. 'src' or '' for projects without src/)
 * @param waPackage - Web Awesome package name (defaults to free package)
 */
export async function generateNextEnvDts(
  cwd: string,
  srcDir: string,
  waPackage: string = WEB_AWESOME_FREE_PACKAGE
): Promise<void> {
  const dtsContent = `/**
 * Web Awesome JSX Types
 *
 * This extends React's JSX.IntrinsicElements with Web Awesome custom elements.
 * Uses the official types from the ${waPackage} package.
 *
 * IMPORTANT: Uses 'declare global' to extend JSX without overwriting React module.
 *
 * @see https://webawesome.com/docs/#react-users
 */

import type {
  CustomElements,
  CustomCssProperties,
} from '${waPackage}/dist/custom-elements-jsx.d.ts';

declare global {
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    interface IntrinsicElements extends CustomElements {}
  }
}

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface CSSProperties extends CustomCssProperties {}
}

export {};
`;

  const dtsPath = path.join(cwd, srcDir, 'web-awesome.d.ts');
  await fs.writeFile(dtsPath, dtsContent);
}

/**
 * Generate theme.css content with customization examples
 *
 * @param config - Kigumi configuration (unused but kept for compatibility)
 * @param tierOverride - Optional tier override (unused but kept for compatibility)
 * @returns CSS content string
 */
export async function generateThemeCSS(): Promise<string> {
  return `/**
 * Web Awesome Theme Customization
 *
 * This file is for your custom CSS overrides.
 * Web Awesome base and theme imports are handled in layers.css.
 *
 * This file is imported into the 'theme' cascade layer,
 * which has higher priority than Web Awesome base styles.
 * This means your customizations will always override Web Awesome defaults.
 *
 * Learn more:
 *   Customizing: https://webawesome.com/docs/customizing
 *   Design Tokens: https://webawesome.com/docs/tokens
 *   CSS Cascade Layers: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
 */

:root {
  /* Your custom CSS variable overrides here */
  /* Example: --wa-color-brand-60: #6366f1; */
}
`;
}

/**
 * Generate or update .gitignore
 */
export async function generateGitIgnore(cwd: string): Promise<void> {
  const gitignorePath = path.join(cwd, '.gitignore');
  const exists = await fs.pathExists(gitignorePath);

  const essentialEntries = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# Build outputs',
    'dist/',
    'build/',
    '',
    '# Kigumi cross-framework staging (transient cache for agent conversion)',
    '.kigumi/foreign/',
    '',
    '# Kigumi registry cache (transient)',
    '.kigumi/cache/',
  ];

  if (!exists) {
    // Create new .gitignore
    const content = essentialEntries.join('\n') + '\n';
    await fs.writeFile(gitignorePath, content);
    return;
  }

  // Update existing .gitignore
  let content = await fs.readFile(gitignorePath, 'utf-8');

  // Add .env if not present
  if (!content.includes('.env')) {
    content += '\n# Environment variables\n.env\n.env.local\n.env.*.local\n';
  }

  // Add .kigumi/foreign/ if not present
  if (!/^\.kigumi\/foreign\/$/m.test(content)) {
    if (!content.endsWith('\n')) {
      content += '\n';
    }
    content +=
      '\n# Kigumi cross-framework staging (transient cache for agent conversion)\n' +
      '.kigumi/foreign/\n';
  }

  // Add .kigumi/cache/ if not present. The cache is rebuilt from the
  // registry on demand; snapshots/ stays tracked because three-way-merge
  // needs them.
  if (!/^\.kigumi\/cache\/$/m.test(content)) {
    if (!content.endsWith('\n')) {
      content += '\n';
    }
    content += '\n# Kigumi registry cache (transient)\n.kigumi/cache/\n';
  }

  await fs.writeFile(gitignorePath, content);
}
