/**
 * Regenerate Utilities
 *
 * PURPOSE: Regenerates auto-generated files (webawesome.ts, layers.css, theme.css, vite-env.d.ts)
 * when configuration changes.
 *
 * EXPORTS:
 * - regenerateWebAwesomeSetup() - Regenerate webawesome.ts + layers.css with theme config
 * - generateLayersCSS() - Generate layers.css with @layer cascade control
 * - generateViteEnvDts() - Generate TypeScript declarations for wa-* elements
 * - generateThemeCSS() - Generate theme.css content
 * - generateGitIgnore() - Create/update .gitignore
 *
 * @see AGENTS.md for auto-generated files list
 */

import fs from 'fs-extra';
import path from 'path';
import { WEB_AWESOME_FREE_PACKAGE } from '../constants.js';
import type { KigumiConfig } from './config.js';
import type { Tier } from './tier.js';
import { detectTierSync, getWebAwesomePackage } from './tier.js';

export interface RegenerateOptions {
  /** Skip regenerating layers.css if it exists (for init command) */
  preserveLayersCSS?: boolean;
}

/**
 * Regenerate the Web Awesome setup file with updated theme configuration
 *
 * This function is used by init and all theme management commands
 * to ensure webawesome.ts and layers.css are always in sync with the config.
 *
 * @param cwd - Current working directory
 * @param config - Kigumi configuration
 * @param utilsDir - Path to utils directory (e.g., 'src/lib')
 * @param tierOverride - Optional tier override (uses .env detection if not provided)
 * @param options - Optional regeneration options
 * @returns Object indicating if layers.css was preserved
 */
export async function regenerateWebAwesomeSetup(
  cwd: string,
  config: KigumiConfig,
  utilsDir: string,
  tierOverride?: Tier,
  options?: RegenerateOptions
): Promise<{ layersPreserved: boolean }> {
  // Detect tier from .env, or use override
  const tier = tierOverride || detectTierSync(cwd);
  const packageName = getWebAwesomePackage(tier);
  const stylesDir = config.stylesDir || 'src/styles';
  const stylesAlias = stylesDir.replace(/^src\//, '@/');

  // Check if layers.css exists and should be preserved
  const layersPath = path.join(cwd, stylesDir, 'layers.css');
  const layersExists = await fs.pathExists(layersPath);
  let layersPreserved = false;

  if (options?.preserveLayersCSS && layersExists) {
    layersPreserved = true;
  } else {
    // Generate layers.css
    const layersContent = await generateLayersCSS(
      packageName,
      config.theme.selected,
      stylesDir
    );
    await fs.writeFile(layersPath, layersContent);
  }

  // Generate theme classes script
  const themeClasses =
    config.theme.selected !== 'none' ? generateThemeClassesScript(config) : '';

  // Generate webawesome.ts that imports layers.css
  const setupFileContent = `/**
 * Web Awesome Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports Web Awesome styles with cascade layers and applies theme classes.
 *
 * Current theme: ${config.theme.selected}
 * Current palette: ${config.theme.palette}
 * Current brand: ${config.theme.brandColor}
 *
 * To change themes, use: kigumi theme <name>
 * To change brand color, use: kigumi brand <color>
 */

// Import Web Awesome CSS with cascade layers for predictable specificity control
import '${stylesAlias}/layers.css';
${themeClasses}
export {};
`;

  const setupFilePath = path.join(cwd, utilsDir, 'webawesome.ts');
  await fs.writeFile(setupFilePath, setupFileContent);

  return { layersPreserved };
}

/**
 * Generate theme classes script for webawesome.ts
 * @internal
 */
function generateThemeClassesScript(config: KigumiConfig): string {
  return `
// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\\bwa-theme-\\S+/g, '')
    .replace(/\\bwa-palette-\\S+/g, '')
    .replace(/\\bwa-brand-\\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-${config.theme.selected}');
  html.classList.add('wa-palette-${config.theme.palette}');
  html.classList.add('wa-brand-${config.theme.brandColor}');
}
`;
}

/**
 * Generate layers.css with @layer imports
 *
 * This file wraps Web Awesome CSS imports in cascade layers for predictable
 * specificity control. Generated by CLI alongside webawesome.ts.
 *
 * @param packageName - Web Awesome package name (e.g., '@awesome.me/webawesome-pro')
 * @param themeName - Selected theme name (e.g., 'tailspin')
 * @param stylesDir - Styles directory path (e.g., 'src/styles')
 * @returns CSS content string
 */
export async function generateLayersCSS(
  packageName: string,
  themeName: string,
  stylesDir: string
): Promise<string> {
  const stylesAlias = stylesDir.replace(/^src\//, '@/');

  return `/**
 * Web Awesome CSS Cascade Layers
 *
 * This file is auto-generated by Kigumi CLI.
 * It wraps Web Awesome CSS in cascade layers for predictable specificity control.
 *
 * Layer hierarchy (earlier = lower priority):
 * 1. base - Web Awesome foundation + theme styles
 * 2. theme - Your custom CSS overrides (theme.css)
 *
 * Learn more: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
 */

/* Define layer order */
@layer base, theme;

/* Layer 1: Web Awesome base styles */
@import '${packageName}/dist/styles/webawesome.css' layer(base);

/* Layer 1: Web Awesome theme styles */
@import '${packageName}/dist/styles/themes/${themeName}.css' layer(base);

/* Layer 2: Your custom CSS overrides */
@import '${stylesAlias}/theme.css' layer(theme);
`;
}

/**
 * Generate vite-env.d.ts with Web Awesome custom element type definitions
 *
 * This file extends React's JSX.IntrinsicElements to include wa-* custom elements,
 * using the official types from the Web Awesome package.
 *
 * See: https://webawesome.com/docs/#react-users
 *
 * @param cwd - Current working directory
 * @param srcDir - Source directory (e.g., 'src')
 * @param waPackage - Web Awesome package name (defaults to free package)
 */
export async function generateViteEnvDts(
  cwd: string,
  srcDir: string,
  waPackage: string = WEB_AWESOME_FREE_PACKAGE
): Promise<void> {
  const viteEnvContent = `/// <reference types="vite/client" />

/**
 * Web Awesome JSX Types
 *
 * This extends React's JSX.IntrinsicElements with Web Awesome custom elements.
 * Uses the official types from the ${waPackage} package.
 *
 * IMPORTANT: Uses 'declare global' to extend JSX without overwriting React module.
 *
 * @see https://webawesome.com/docs/#react-users
 */

import type {
  CustomElements,
  CustomCssProperties,
} from '${waPackage}/dist/custom-elements-jsx.d.ts';

declare global {
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    interface IntrinsicElements extends CustomElements {}
  }
}

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface CSSProperties extends CustomCssProperties {}
}

export {};
`;

  const viteEnvPath = path.join(cwd, srcDir, 'vite-env.d.ts');
  await fs.writeFile(viteEnvPath, viteEnvContent);
}

/**
 * Generate theme.css content with customization examples
 *
 * @param config - Kigumi configuration (unused but kept for compatibility)
 * @param tierOverride - Optional tier override (unused but kept for compatibility)
 * @returns CSS content string
 */
export async function generateThemeCSS(): Promise<string> {
  return `/**
 * Web Awesome Theme Customization
 *
 * This file is for your custom CSS overrides.
 * Web Awesome base and theme imports are handled in layers.css.
 *
 * This file is imported into the 'theme' cascade layer,
 * which has higher priority than Web Awesome base styles.
 * This means your customizations will always override Web Awesome defaults.
 *
 * Learn more:
 *   Customizing: https://webawesome.com/docs/customizing
 *   Design Tokens: https://webawesome.com/docs/tokens
 *   CSS Cascade Layers: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
 */

:root {
  /* Your custom CSS variable overrides here */
  /* Example: --wa-color-brand-600: #6366f1; */
}
`;
}

/**
 * Generate or update .gitignore
 */
export async function generateGitIgnore(cwd: string): Promise<void> {
  const gitignorePath = path.join(cwd, '.gitignore');
  const exists = await fs.pathExists(gitignorePath);

  const essentialEntries = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# Build outputs',
    'dist/',
    'build/',
  ];

  if (!exists) {
    // Create new .gitignore
    const content = essentialEntries.join('\n') + '\n';
    await fs.writeFile(gitignorePath, content);
  } else {
    // Update existing .gitignore
    let content = await fs.readFile(gitignorePath, 'utf-8');

    // Add .env if not present
    if (!content.includes('.env')) {
      content += '\n# Environment variables\n.env\n.env.local\n.env.*.local\n';
    }

    await fs.writeFile(gitignorePath, content);
  }
}
