import fs from 'fs-extra';
import path from 'path';
import type { KigumiConfig } from './config.js';

import type { Tier } from './tier.js';
import { detectTierSync } from './tier.js';

/**
 * Regenerate the Web Awesome setup file with updated theme configuration
 *
 * This function is used by init and all theme management commands
 * to ensure webawesome.ts is always in sync with the config.
 */
export async function regenerateWebAwesomeSetup(
  cwd: string,
  config: KigumiConfig,
  utilsDir: string,
  tierOverride?: Tier
): Promise<void> {
  // Detect tier from .env, or use override
  const tier = tierOverride || detectTierSync(cwd);
  const packageName =
    tier === 'pro' ? '@awesome.me/webawesome-pro' : '@awesome.me/webawesome';

  // Base Web Awesome CSS (required for all components and CSS variables)
  const baseImport = `import '${packageName}/dist/styles/webawesome.css';`;

  // Determine theme CSS import path
  let themeImport = '';
  if (config.theme.selected !== 'none') {
    const themeName = config.theme.selected;
    themeImport = `import '${packageName}/dist/styles/themes/${themeName}.css';`;
  }

  // User overrides import (uses @/ alias - user must configure in vite.config.ts)
  const userOverridesImport = `import '@/styles/theme.css';`;

  // Generate runtime script to set HTML classes
  const themeClasses =
    config.theme.selected !== 'none'
      ? `
// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\\bwa-theme-\\S+/g, '')
    .replace(/\\bwa-palette-\\S+/g, '')
    .replace(/\\bwa-brand-\\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-${config.theme.selected}');
  html.classList.add('wa-palette-${config.theme.palette}');
  html.classList.add('wa-brand-${config.theme.brandColor}');
}
`
      : '';

  const setupFileContent = `/**
 * Web Awesome Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports Web Awesome styles and applies theme classes to the <html> element.
 *
 * Current theme: ${config.theme.selected}
 * Current palette: ${config.theme.palette}
 * Current brand: ${config.theme.brandColor}
 *
 * To change themes, use: kigumi theme set <name>
 * To change brand color, use: kigumi brand set <color>
 */

// Import base Web Awesome CSS (includes all CSS variables and component styles)
${baseImport}

// Import selected theme CSS
${themeImport}

// Import your custom theme overrides
${userOverridesImport}
${themeClasses}
export {};
`;

  const setupFilePath = path.join(cwd, utilsDir, 'webawesome.ts');
  await fs.writeFile(setupFilePath, setupFileContent);
}

/**
 * Generate vite-env.d.ts with Web Awesome custom element type definitions
 *
 * This file extends React's JSX.IntrinsicElements to include wa-* custom elements,
 * fixing TypeScript errors when using Web Awesome components in React.
 *
 * See: https://webawesome.com/docs/#react-users
 */
export async function generateViteEnvDts(
  cwd: string,
  srcDir: string
): Promise<void> {
  const viteEnvContent = `/// <reference types="vite/client" />

import 'react';

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'wa-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        class?: string;
        variant?: string;
        appearance?: string;
        size?: string;
        pill?: boolean;
        disabled?: boolean;
        loading?: boolean;
        'with-caret'?: boolean;
        href?: string;
        target?: string;
        download?: string;
        rel?: string;
        'data-dialog'?: string;
      };
      'wa-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        class?: string;
        type?: string;
        label?: string;
        hint?: string;
        placeholder?: string;
        value?: string;
        appearance?: string;
        size?: string;
        pill?: boolean;
        disabled?: boolean;
        'with-clear'?: boolean;
        'password-toggle'?: boolean;
      };
      'wa-card': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        class?: string;
        appearance?: string;
        orientation?: string;
        'with-header'?: boolean;
        'with-footer'?: boolean;
        'with-media'?: boolean;
      };
      'wa-dialog': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        class?: string;
        open?: boolean;
        label?: string;
        'without-header'?: boolean;
        'light-dismiss'?: boolean;
      };
    }
  }
}
`;

  const viteEnvPath = path.join(cwd, srcDir, 'vite-env.d.ts');
  await fs.writeFile(viteEnvPath, viteEnvContent);
}

/**
 * Generate theme.css content
 */
export async function generateThemeCSS(config: KigumiConfig, tierOverride?: Tier): Promise<string> {
  const { theme } = config;
  
  // Detect tier from .env if not provided
  const tier = tierOverride || 'free'; // Will be determined by caller
  const packageName =
    tier === 'pro' ? '@awesome.me/webawesome-pro' : '@awesome.me/webawesome';

  return `/**
 * Web Awesome Theme Configuration
 *
 * Theme: ${theme.selected}
 * Palette: ${theme.palette}
 * Brand Color: ${theme.brandColor}
 */

/* Import Web Awesome theme */
@import '${packageName}/dist/styles/themes/${theme.selected}.css';

/* Apply palette and brand color */
:root {
  --wa-palette: ${theme.palette};
  --wa-brand-color: ${theme.brandColor};
}

/* Custom theme overrides */
/* Add your custom CSS here */
`;
}

/**
 * Generate or update .gitignore
 */
export async function generateGitIgnore(cwd: string): Promise<void> {
  const gitignorePath = path.join(cwd, '.gitignore');
  const exists = await fs.pathExists(gitignorePath);

  const essentialEntries = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# Build outputs',
    'dist/',
    'build/',
  ];

  if (!exists) {
    // Create new .gitignore
    const content = essentialEntries.join('\n') + '\n';
    await fs.writeFile(gitignorePath, content);
  } else {
    // Update existing .gitignore
    let content = await fs.readFile(gitignorePath, 'utf-8');

    // Add .env if not present
    if (!content.includes('.env')) {
      content += '\n# Environment variables\n.env\n.env.local\n.env.*.local\n';
    }

    await fs.writeFile(gitignorePath, content);
  }
}
