/**
 * Web Awesome Setup
 *
 * This file is auto-generated by Kigumi CLI.
 * It imports Web Awesome styles and applies theme classes to the <html> element.
 *
 * Current theme: brutalist
 * Current palette: rudimentary
 * Current brand: purple
 *
 * To change themes, use: kigumi theme set <name>
 * To change brand color, use: kigumi brand set <color>
 */

// Import base Web Awesome CSS (includes all CSS variables and component styles)
import '@awesome.me/webawesome-pro/dist/styles/webawesome.css';

// Import selected theme CSS
import '@awesome.me/webawesome-pro/dist/styles/themes/brutalist.css';

// Import your custom theme overrides
import '@/styles/theme.css';

// Apply theme classes to <html> element
if (typeof document !== 'undefined') {
  const html = document.documentElement;

  // Remove old theme classes (for hot reload)
  html.className = html.className
    .replace(/\bwa-theme-\S+/g, '')
    .replace(/\bwa-palette-\S+/g, '')
    .replace(/\bwa-brand-\S+/g, '');

  // Add new theme classes
  html.classList.add('wa-theme-brutalist');
  html.classList.add('wa-palette-rudimentary');
  html.classList.add('wa-brand-purple');
}

export {};
