/**
 * Migration Utility
 *
 * PURPOSE: Handles Free ↔ Pro package migration for tier upgrades/downgrades.
 *
 * WHY: When users upgrade from Free to Pro (or downgrade), all import statements
 * need to change from @awesome.me/webawesome to @awesome.me/webawesome-pro (or vice versa).
 * This includes generated files and user components.
 *
 * @see AGENTS.md Rule #11 for Free→Pro migration
 * @see AGENTS.md Rule #12 for tier migration architecture
 */

import fs from 'fs-extra';
import path from 'path';
import {
  FREE_PACKAGE_REGEX,
  PRO_PACKAGE_REGEX,
  WEB_AWESOME_FREE_PACKAGE,
  WEB_AWESOME_PRO_PACKAGE,
} from '../../constants.js';
import type { OutputInterface } from '../../output/types.js';

/**
 * Static files that always need migration
 * WHY: These are generated by kigumi init and contain package imports
 */
const STATIC_MIGRATION_FILES = [
  'src/lib/webawesome.ts',
  'src/lib/webawesome.js',
  'src/styles/theme.css',
  'src/types/web-awesome.d.ts',
  'src/vite-env.d.ts',
];

/** File extensions to scan for migration in components directory */
const COMPONENT_EXTENSIONS = ['.tsx', '.jsx', '.ts', '.js', '.vue'];

/**
 * Recursively find all files matching patterns in a directory
 *
 * @internal
 */
async function findFiles(dir: string, extensions: string[]): Promise<string[]> {
  const files: string[] = [];

  async function scan(currentDir: string): Promise<void> {
    if (!(await fs.pathExists(currentDir))) {
      return;
    }

    const entries = await fs.readdir(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);

      if (entry.isDirectory()) {
        await scan(fullPath);
      } else if (entry.isFile()) {
        if (extensions.some((ext) => entry.name.endsWith(ext))) {
          files.push(fullPath);
        }
      }
    }
  }

  await scan(dir);
  return files;
}

/**
 * Get all files that need migration
 *
 * @internal
 */
async function getMigrationFiles(cwd: string): Promise<string[]> {
  // Find all component files (Bug #1 fix)
  const componentsDir = path.join(cwd, 'src/components/ui');
  const componentFiles = await findFiles(componentsDir, COMPONENT_EXTENSIONS);

  // Combine static files with component files
  return [
    ...STATIC_MIGRATION_FILES.map((f) => path.join(cwd, f)),
    ...componentFiles,
  ];
}

/**
 * Migrate package references from Free to Pro
 *
 * Replaces @awesome.me/webawesome → @awesome.me/webawesome-pro
 * in ALL generated files (including component files)
 *
 * @param cwd - Current working directory
 * @param output - Output interface for logging
 */
export async function migratePackageReferences(
  cwd: string,
  output: OutputInterface
): Promise<void> {
  const spinner = output.spinner('Migrating package references...');

  try {
    const allFiles = await getMigrationFiles(cwd);
    let migratedCount = 0;

    for (const filePath of allFiles) {
      if (!(await fs.pathExists(filePath))) {
        continue;
      }

      const content = await fs.readFile(filePath, 'utf-8');
      // Use regex from constants - matches Free but NOT Pro package
      const newContent = content.replace(
        FREE_PACKAGE_REGEX,
        WEB_AWESOME_PRO_PACKAGE
      );

      if (newContent !== content) {
        await fs.writeFile(filePath, newContent);
        migratedCount++;
        const relativePath = path.relative(cwd, filePath);
        output.log(`[DEBUG] Migrated: ${relativePath}`);
      }
    }

    spinner.stop(`Migrated ${migratedCount} file(s)`);

    if (migratedCount > 0) {
      output.success('Migration complete!');
      output.note(
        'Migrated files',
        'Package references updated from Free to Pro.\n' +
          'All generated files have been updated.'
      );
    }
  } catch (error) {
    spinner.error('Migration failed');
    throw error;
  }
}

/**
 * Reverse migrate package references from Pro to Free (Bug #2 fix)
 *
 * Replaces @awesome.me/webawesome-pro → @awesome.me/webawesome
 * in ALL generated files (including component files)
 *
 * WHY: When user removes Pro token and wants to downgrade, all imports
 * need to be reverted to the Free package.
 *
 * @param cwd - Current working directory
 * @param output - Output interface for logging
 */
export async function reverseMigratePackageReferences(
  cwd: string,
  output: OutputInterface
): Promise<void> {
  const spinner = output.spinner('Reverse migrating package references...');

  try {
    const allFiles = await getMigrationFiles(cwd);
    let migratedCount = 0;

    for (const filePath of allFiles) {
      if (!(await fs.pathExists(filePath))) {
        continue;
      }

      const content = await fs.readFile(filePath, 'utf-8');
      // Use regex from constants - matches Pro package
      const newContent = content.replace(
        PRO_PACKAGE_REGEX,
        WEB_AWESOME_FREE_PACKAGE
      );

      if (newContent !== content) {
        await fs.writeFile(filePath, newContent);
        migratedCount++;
        const relativePath = path.relative(cwd, filePath);
        output.log(`[DEBUG] Reverse migrated: ${relativePath}`);
      }
    }

    spinner.stop(`Reverse migrated ${migratedCount} file(s)`);

    if (migratedCount > 0) {
      output.success('Reverse migration complete!');
      output.note(
        'Reverse migrated files',
        'Package references updated from Pro to Free.\n' +
          'All generated files have been updated.'
      );
    }
  } catch (error) {
    spinner.error('Reverse migration failed');
    throw error;
  }
}
